CREATE TABLE Class (
    id INT PRIMARY KEY,
    name VARCHAR(50)
);


INSERT INTO Class VALUES (1,"Ram");
INSERT INTO Class VALUES (2,"Sam");
INSERT INTO Class VALUES (3."Raj");

SELECT * FROM Class;

START TRANSACTION;

INSERT INTO Class VALUES (4,"Sham");
ROLLBACK; 

INSERT INTO Class VALUES (4,"Sham");
COMMIT;

START TRANSACTION;
SAVEPOINT Point;
INSERT INTO Class VALUES (5,"Helen");
ROLLBACK TO Point;

COMMIT;
